### ISSUE TITLE
Service tab is empty after "composer update"

### ISSUE THREAD

**Issue by akropivko** [aimeos/ai-admin-jqadm#191]
**Environment**
1. Version (e.g. 2020.10)
2. Integration (Laravel)
3. System (Windows)

**Describe the bug**
I've update composer via "composer update" command and Service tab is empty now, see animated gif
![sevices](https://user-images.githubusercontent.com/66216139/118281325-c28d3580-b4d5-11eb-882b-3596627af314.gif)

**Comment by aimeos** [comment]
Can you please post the output of `composer show`?

**Comment by akropivko** [comment]
Sure! see compshow.txt
[compshow.txt](https://github.com/aimeos/ai-admin-jqadm/files/6479414/compshow.txt)

And if you need the previous one (everything's ok) - compshow_before.txt
[compshow_before.txt](https://github.com/aimeos/ai-admin-jqadm/files/6479420/compshow_before.txt)

**Comment by aimeos** [comment]
This is the case when a JS error occurs in the Vue template. Before, this has occured most often by a value that contains a newline character within a simple JS string (`'\n'`). We have fixed that in the latest version but there seems to be something elso now.

To debug, you have to install the Vue Devtools (Chrome and Firefox only) and change the `./vendor/aimeos/aimeos-laravel/src/views/jqadm/index.blade.php` file by removing the `.min` from
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.12/vue.min.js"></script>
```
Then, the browser console will show the errors from the Vue templates.

**Comment by akropivko** [comment]
thanks!

**Comment by akropivko** [comment]
Sorry, but there is no such line there (...vue/2.6.12/vue.min.js), see attach.
[index.blade.zip](https://github.com/aimeos/ai-admin-jqadm/files/6514606/index.blade.zip)

Also Vue.js not detected by default
![Screenshot_18](https://user-images.githubusercontent.com/66216139/118954943-eda8d680-b966-11eb-8e5d-09859adca581.jpg)

**Comment by aimeos** [comment]
It's included here: https://github.com/aimeos/aimeos-laravel/blob/2020.10/src/views/jqadm/index.blade.php#L28

**Comment by akropivko** [comment]
ok, here is the log from console (see below). please let me know if you need something else
[127.0.0.1-1621504208297.log](https://github.com/aimeos/ai-admin-jqadm/files/6514845/127.0.0.1-1621504208297.log)

**Comment by akropivko** [comment]
It seems I've solved the issue. The problem was with ' symbol in service label. Removing it from db row solves the problem. 
I'm not sure if you need to do something with this.
Anyway, thanks a lot for your help!

**Comment by aimeos** [comment]
The problem with backticks is now solved in dev-master, 2021.04.x-dev and 2020.10.x-dev. Can you execute
```
composer req aimeos/aimeos-core:2020.10.x-dev
```
and check if it works for you too?

**Comment by akropivko** [comment]
Sure.
It works for ' but it still doesn't work for `
![Screenshot_20](https://user-images.githubusercontent.com/66216139/118969316-965e3280-b975-11eb-85ed-2c25b9c5878e.jpg)

**Comment by aimeos** [comment]
Please check if you have the latest version (commit: 48f4ba97bb5fb60134338be7d25645d65d3483bf)

**Comment by akropivko** [comment]
It seems I have another version - ...48f4ba9 , see screen below.
How can I get the latest one? composer update doesn't help (do nothing)

![Screenshot_21](https://user-images.githubusercontent.com/66216139/118994349-ebf30900-b98e-11eb-912a-2fd169486dbc.jpg)

**Comment by akropivko** [comment]
oh, sorry. so YES, the version is the same. And it is work already, I don't know why it didn't work before. Sorry for that.
Thanks again for your product!

**Comment by akropivko** [comment]
Sorry again. But NO, it doesn't work on the page.
The version is the same

![Screenshot_21](https://user-images.githubusercontent.com/66216139/118995539-e5b15c80-b98f-11eb-82f4-4f82bec3b55d.jpg)

**Comment by aimeos** [comment]
OK, now it's fixed in aimeos/aimeos-core:2020.10.x-dev (commit: 7de37b79bbe449597b6fbcfe445ff40363e5db51)

**Comment by akropivko** [comment]
Thanks!
